version: '3.7'
services:

  xtrack-server:
    build:
      context: ./xtrack-server
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: always
    container_name: xtrack-server
    network_mode: host
    hostname: localhost


  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=xtrackdb
    container_name: xtrackdb
    network_mode: host
    hostname: localhost
