
name: Generate APK
on:
  push:
    branches:
      - stage-app
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      # need to setup java 8 to build and compile ionic/cordova app
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Following cmds fail without sudo
      - name: Install Cordova
        run: sudo npm install -g cordova

      - name: Install Ionic
        run: sudo npm install -g @ionic/cli

      - name: Install app dependencies
        run: cd  xtrack-app/xtrack-app && npm install


      # without the below install NDK step, final build fails
      - name: Install NDK
        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Build Android Release APK
        run: cd xtrack-app/xtrack-app && ionic cordova build android --release --prod 

      - name: Generate the Android App Bundle
        working-directory: ./xtrack-app/xtrack-app/platforms/android/
        run: ./gradlew bundle

      - name: Upload unsigned APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: ./xtrack-app/xtrack-app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Upload release bundle
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: ./xtrack-app/xtrack-app/platforms/android/app/build/outputs/bundle/release/app-release.aab
