name: Deploy to EC2
on:
  push:
    branches:
      - stage
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.PROD_SERVER }}
    - name: deploy over ssh
      run: chmod 777 ./ssh_to_server.sh && export PROD_SERVER=${{ secrets.PROD_SERVER }} && export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} && export MYSQL_DB=${{ secrets.MYSQL_DB }} && ./ssh_to_server.sh